name: mari_pesan_sdk
description: Mari Pesan SDK
version: 0.0.1
homepage: https://github.com/elnco-cloud/mari_pesan_sdk

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1
  firebase_messaging: ^11.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.6.0
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  form_validator: ^1.0.2
  get: ^4.6.5
  http_parser: ^4.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+2
  path: ^1.8.1
  sprintf: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
